Upgrade script
bancorprotocol/carbon-contracts pull request #94
Opened 2023-06-01 15:42 UTC by ivanzhelyazkov

Add upgrade script and post-upgrade tests for CarbonController

2023-06-04 22:18 UTC, lbeder approved these changes

2023-06-05 11:53 UTC, yudilevi requested changes

2023-06-05 11:53 UTC, yudilevi commented on contracts/utility/MathEx.sol
> +     * @dev returns the smallest integer `z` such that `x * y / z <= 2 ^ 256 - 1`
not merged from dev?

2023-06-05 11:53 UTC, yudilevi commented on deploy/scripts/0005-CarbonController-upgrade.ts
> +import { DeployedContracts, InstanceName, isMainnet, setDeploymentMetadata, upgradeProxy } from '../../utils/Deploy';
run linter

2023-06-05 11:53 UTC, yudilevi commented on deploy/scripts/0005-CarbonController-upgrade.ts
> +        from: daoMultisig,
I believe it should be `deployer` here

2023-06-05 14:45 UTC, ivanzhelyazkov commented on contracts/utility/MathEx.sol
> +     * @dev returns the smallest integer `z` such that `x * y / z <= 2 ^ 256 - 1`
fixed

2023-06-05 14:45 UTC, ivanzhelyazkov commented on deploy/scripts/0005-CarbonController-upgrade.ts
> +import { DeployedContracts, InstanceName, isMainnet, setDeploymentMetadata, upgradeProxy } from '../../utils/Deploy';
fixed lint issues

2023-06-05 18:43 UTC, lbeder commented on deploy/scripts/0005-CarbonController-upgrade.ts
> +        from: daoMultisig,
How come the tests passed?

2023-06-05 19:18 UTC, merged